### ISSUE TITLE
Latest update results in UserCodeSyntaxError

### ISSUE THREAD

**Issue by tkadlec** [enhance-dev/arc-plugin-enhance#127]
I opened a thread in Discord too, but putting it here for posterity. 

I _think_ the latest update (https://github.com/enhance-dev/arc-plugin-enhance/commit/88d742bf1d0bf43a0424e360b9aa3565c097f154) is the root cause of a "Runtime.UserCodeSyntaxError" currently taking down my app.

Here's the exact error:

```
{
    "errorType": "Runtime.UserCodeSyntaxError",
    "errorMessage": "SyntaxError: Named export 'pathToRegexp' not found. The requested module 'path-to-regexp' is a CommonJS module, which may not support all module.exports as named exports.\nCommonJS modules can always be imported via the default export, for example using:\n\nimport pkg from 'path-to-regexp';\nconst { pathToRegexp } = pkg;\n",
    "stack": [
        "Runtime.UserCodeSyntaxError: SyntaxError: Named export 'pathToRegexp' not found. The requested module 'path-to-regexp' is a CommonJS module, which may not support all module.exports as named exports.",
        "CommonJS modules can always be imported via the default export, for example using:",
        "",
        "import pkg from 'path-to-regexp';",
        "const { pathToRegexp } = pkg;",
        "",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1084:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}
```

Let me know if there are any other helpful details I can provide to help you dive in.

**Comment by tkadlec** [comment]
Closing this. The change was the fix, not the cause.

If anyone stumbles on this, upgrade `arc-plugin-enhance` to 11.0.4.
