### ISSUE TITLE
Database backed sessions fail with Enhance

### ISSUE THREAD

**Issue by ryanbethel** [enhance-dev/arc-plugin-enhance#96]
Database backed sessions fail when used with Enhance. I am not sure where the bug is. It is probably not in the CLI. It may be in sandbox, but this bug does not seem to reproduce with architect on its own so seems like it is related to enhance in some way.

Reproduction:
1. `begin new .`
2. Add the session table info to `.arc`
```arc
@tables
sessions 
  _idx * 
  ttl ttl 
```
3. Add the environment variable to the `.env` file (`ARC_SESSION_TABLE_NAME=sessions`)

When you launch sandbox and hit any route it you get the following error:
```
ResourceNotFoundException: Requested resource not found
    at de_ResourceNotFoundExceptionRes (/Users/ryanbethel/_PARA_Local/code-projects/consulting/begin-com/quick-map/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:2878:23)
    at de_PutItemCommandError (/Users/ryanbethel/_PARA_Local/code-projects/consulting/begin-com/quick-map/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:1893:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/ryanbethel/_PARA_Local/code-projects/consulting/begin-com/quick-map/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /Users/ryanbethel/_PARA_Local/code-projects/consulting/begin-com/quick-map/node_modules/@aws-sdk/lib-dynamodb/dist-cjs/baseCommand/DynamoDBDocumentClientCommand.js:26:34
    at async /Users/ryanbethel/_PARA_Local/code-projects/consulting/begin-com/quick-map/node_modules/@aws-sdk/client-dynamodb/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
    at async /Users/ryanbethel/_PARA_Local/code-projects/consulting/begin-com/quick-map/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /Users/ryanbethel/_PARA_Local/code-projects/consulting/begin-com/quick-map/node_modules/@aws-sdk/client-dynamodb/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'KA2GJVPJSJCV1CRFYH1FRYQQ2ZODDJB6LA5SZJSDJV62QQOIGI0A',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  __type: 'com.amazonaws.dynamodb.v20120810#ResourceNotFoundException'
```

I suspect this is an aws v3 SDK bug, but I am not sure.

**Comment by ryanbethel** [comment]
@ryanblock Does this look at all familiar to you? It looks like this could be related to the V3 SDK, and you know the sessions/sandbox code better than anyone.

**Comment by ryanbethel** [comment]
@kristoferjoseph or @tbeseda does this error look familiar to either of you? I am pretty sure this is an aws SDK related bug but I can't track it down.
